### ISSUE TITLE
Ungünstige Farbe, da man sie auf dem Hintergrund nicht erkennen kann. Ansonsten top.

### ISSUE THREAD

**Issue by Max-Wolfram** [T-systemsYoungsters/leon-LOGIST#13]
https://github.com/T-systemsYoungsters/leon-LOGIST/blob/79744532ab300814697137933e863f00800b199e/pythonlernen/Labs/Chapter%208%20Lab.py#L18

**Comment by Lmsr92** [comment]
Fixed
